/* Autogenerated by png2wx.pl on Sun Nov  3 17:37:01 2019 */
#ifndef _ICONS_H
#define _ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_plus;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;
extern wxBitmap *_img_dashboard;
extern wxBitmap *_img_engine;
extern wxBitmap *_img_gauge_background;


#endif /* _ICONS_H */
